openapi: 3.0.0
info:
  title: Online Library API
  version: 1.0.0
  description: API for managing books, authors, genres, and favorites.

servers:
  - url: http://localhost:8000
    description: Local development server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Book:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        publishedYear:
          type: integer
        isbn:
          type: string
        authors:
          type: array
          items:
            $ref: '#/components/schemas/Author'
        genres:
          type: array
          items:
            $ref: '#/components/schemas/Genre'

    Author:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string

    Genre:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string

    User:
      type: object
      properties:
        email:
          type: string
        password:
          type: string

paths:
  /api/register:
    post:
      summary: Register a new user
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Invalid input or user already exists

  /api/login_check:
    post:
      summary: Login to get JWT token
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: Invalid credentials

  /api/books:
    get:
      summary: Get list of all books
      tags:
        - Books
      responses:
        '200':
          description: A list of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
    post:
      summary: Create a new book
      tags:
        - Books
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                publishedYear:
                  type: integer
                isbn:
                  type: string
                authors:
                  type: array
                  items:
                    type: string
                genres:
                  type: array
                  items:
                    type: string
      responses:
        '201':
          description: Book created
        '400':
          description: Invalid data
        '403':
          description: Forbidden (Admin only)

  /api/books/{id}:
    get:
      summary: Get a single book by ID
      tags:
        - Books
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Book details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '404':
          description: Book not found
    delete:
      summary: Delete a book
      tags:
        - Books
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Book deleted
        '404':
          description: Book not found
        '403':
          description: Forbidden (Admin only)

  /api/favorites/{id}:
    post:
      summary: Add a book to favorites
      tags:
        - Favorites
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Added to favorites
        '401':
          description: Unauthorized
        '404':
          description: Book not found
    delete:
      summary: Remove a book from favorites
      tags:
        - Favorites
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Removed from favorites
        '401':
          description: Unauthorized
        '404':
          description: Book not found

  /api/export/books:
    get:
      summary: Export books to CSV
      tags:
        - Export
      security:
        - bearerAuth: []
      responses:
        '200':
          description: CSV file
          content:
            text/csv:
              schema:
                type: string
                format: binary
        '403':
          description: Forbidden (Admin only)
