<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260127150715 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE author ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE author ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE book ADD createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE book ADD updatedAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE book DROP created_at');
        $this->addSql('ALTER TABLE book DROP updated_at');
        $this->addSql('ALTER TABLE book ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE book ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX idx_c16a6d8f16a2b381 RENAME TO IDX_8D92268116A2B381');
        $this->addSql('ALTER INDEX idx_c16a6d8f4296d31f RENAME TO IDX_8D9226814296D31F');
        $this->addSql('ALTER TABLE genre ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE genre ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE "user" ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE "user" ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE Author ALTER id SET DEFAULT nextval(\'author_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE Author ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE Book ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE Book ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE Book DROP createdAt');
        $this->addSql('ALTER TABLE Book DROP updatedAt');
        $this->addSql('ALTER TABLE Book ALTER id SET DEFAULT nextval(\'book_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE Book ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN Book.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN Book.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER INDEX idx_8d92268116a2b381 RENAME TO idx_c16a6d8f16a2b381');
        $this->addSql('ALTER INDEX idx_8d9226814296d31f RENAME TO idx_c16a6d8f4296d31f');
        $this->addSql('ALTER TABLE Genre ALTER id SET DEFAULT nextval(\'genre_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE Genre ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE "user" ALTER id SET DEFAULT nextval(\'user_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE "user" ALTER id DROP IDENTITY');
    }
}
